### ISSUE TITLE
fail to load stored model outside of MCMatlab

### ISSUE THREAD

**Issue by merlelosch** [ankrh/MCmatlab#7]
Hey there! Great MC simulation program which I use a lot.

For organizational purposes, I would like to store the models created when running a simulation in a separate folder. However, I realized that after saving the model, loading is only possible within MCMatlab. When trying to open a stored model from a different folder, I get the following message:
```
Warning: Variable 'model' originally saved as a MCmatlab.model cannot be instantiated as an object and will be read in as a uint32.
> In uiimport/runImportdata (line 487)
  In uiimport/gatherFilePreviewData (line 466)
  In uiimport (line 277)
```
To avoid that issue, I suggest to store the model using primitive types.

Cheers,
Merle

**Comment by ankrh** [comment]
Hi Merle!

Hope you're doing well - I remember talking with you at the last Biophotonics Summer School on Hven!

Anyway, Dominik and I looked into the issue you're describing and how to solve it.

You can load MCmatlab objects from other folders, but only if MATLAB can locate the +MCmatlab folder (the class definition). MATLAB will look for it in first in the current working directory and secondly in the folders on the MATLAB path. You could use the addpath(...) function or take inspiration from this question: [https://se.mathworks.com/matlabcentral/answers/116177-how-to-add-a-folder-permanently-to-matlab-path](https://se.mathworks.com/matlabcentral/answers/116177-how-to-add-a-folder-permanently-to-matlab-path)

We actually used to use a primitive struct for the model "object", as you suggest, but it became increasingly unwieldy and we had to switch to a proper object at one point due to the increasing complexity of MCmatlab. So we can't really go back to primitives.

We also considered whether an informative error message could be generated when someone tries to load an MCmatlab model object without MATLAB being able to locate the class definition, but we didn't find a way to be able to do that.

So in lack of a better option, we will write a small section into the readme file explaining what I've written here, and we hope people will be able to find it.

I hope the above helps you out. Let us know if this works for you.

**Comment by merlelosch** [comment]
Hi Anders,

Indeed we did meet at the summer school last year - what an impressive week that was...

Thanks for looking into this issue. I did not encounter it using the previous version of MCMatlab, but the switch from a primitive struct to a proper object with this version explains it. A more informative error message would indeed have helped me in figuring out what is wrong, as - once you know - adding the +MCmatlab folder to the Matlab path is an easy solution. I hope you can find a way to generate one. In the meantime, adjusting the readme file seems like a good idea!

All the best,
Merle
